Update links to resources on modelica.org
modelica/fmi-standard.org pull request #305
Opened 2021-05-12 09:10 UTC by t-sommer

2021-07-14 19:09 UTC, beutlich reviewed
Not sure if ready for review since it still is a draft PR.

2021-07-14 19:09 UTC, beutlich commented on _posts/2017-05-15-fmi-user-meeting-prague.md
> +You can get the agenda [here](https://web.archive.org/web/20181116092352/https://www.modelica.org/events/modelica2017/documents/fmi-user-meeting).
```suggestion
You can get the agenda [here](https://2017.international.conference.modelica.org/fmi-user-meeting.html).
```

2021-09-02 17:35 UTC, chrbertsch approved these changes

2021-09-02 17:43 UTC, chrbertsch requested changes
There are still some links broken to files that were prevously on SVN.

* [Overview of the FMI, DCP and SSP standards](https://svn.fmi-standard.org/fmi/branches/public/docs/Modelica2019/Industrial_User_Presentations_Modelica2019/001_Overview_FMI_SSP_DCP.pdf)
* [Usage of FMI at Bosch - status and outlook](https://svn.fmi-standard.org/fmi/branches/public/docs/Modelica2019/Industrial_User_Presentations_Modelica2019/2808_Usage_FMI_Bosch.pdf)
* [Co-Simulation scenarios in industrial production plants](https://svn.fmi-standard.org/fmi/branches/public/docs/Modelica2019/Industrial_User_Presentations_Modelica2019/Presentation_CoSimulatedPlants_ModelicaFMI_2019_final.pdf)
* [Enhancing the Model Integration Workflow in Aircraft System Simulation using FMI & SSP](https://svn.fmi-standard.org/fmi/branches/public/docs/Modelica2019/Industrial_User_Presentations_Modelica2019/Saab_Eek_MC2019.pdf)

@t-sommer: Where shall we put the these files? To https://github.com/modelica/fmi-standard.org/tree/master/assets?

Do we have the PDFs any more? @MABackoffice : is there a backup of the SVN?

Some of the PPT files are here https://github.com/modelica/fmi-design/tree/master/Meetings/2019/2019-03-04-FMI-User-Meeting/Presentations but not all. 

We could also merge the PR and fix the remaining issues later

2021-09-07 11:15 UTC, chrbertsch commented
Superceeded by #330

2021-09-07 11:15 UTC, closed without merging